version: "3.3"

networks:
  corp:
    driver: bridge

services:
  demeter:
    build:
      args:
        NODE_ENV: "production"
      context: .
      dockerfile: ./apps/tech-inspect-bff/Dockerfile
    container_name: tech-inspect-bff
    environment:
      NODE_ENV: "production"
      PORT: 8080
    image: us-east1-docker.pkg.dev/vitorblsantos/tech-inspect-bff:latest
    networks:
      - corp
    ports:
      - 8080:8080
    restart: on-failure
