version: "3.3"

networks:
  corp:
    driver: bridge

services:
  tech-inspect-bff:
    build:
      args:
        NODE_ENV: "production"
      context: .
      dockerfile: Dockerfile
    container_name: tech-inspect-bff
    environment:
      NODE_ENV: "production"
      PORT: 8080
    image: us.gcr.io/vitorblsantos/tech-inspect-bff:latest
    networks:
      - corp
    ports:
      - 8080:8080
    restart: on-failure
