name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  auth:
    runs-on: ubuntu-latest
    needs: checkout
    environment: production
    steps:
      - name: Authenticate to Google Cloud
        run: |
          touch service-account-key.json
          echo "${{ secrets.SERVICE_ACCOUNT }}" | base64 --decode > service-account-key.json
          gcloud auth activate-service-account --key-file=service-account-key.json
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us.gcr.io
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}

  setup-project-id:
    runs-on: ubuntu-latest
    needs: auth
    environment: production
    steps:
      - name: Set Google Cloud Project
        run: gcloud config set project $PROJECT_ID
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}

  build-docker-image:
    runs-on: ubuntu-latest
    needs: setup-project-id
    environment: production
    steps:
      - name: Build Docker Images
        run: docker compose build

  push-docker-image:
    runs-on: ubuntu-latest
    needs: build-docker-image
    environment: production
    steps:
      - name: Push Docker Images
        run: docker compose push

  replace-service:
    runs-on: ubuntu-latest
    needs: push-docker-image
    environment: production
    steps:
      - name: Replace Cloud Run Service
        run: gcloud run services replace ./app.yaml --project $PROJECT_ID
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}

  update-service:
    runs-on: ubuntu-latest
    needs: replace-service
    environment: production
    steps:
      - name: Update Cloud Run Service
        run: gcloud run services update $SERVICE_NAME --project $PROJECT_ID --region us-central1
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}

  update-iam-policy:
    runs-on: ubuntu-latest
    needs: update-service
    environment: production
    steps:
      - name: Add IAM Policy Binding for Cloud Run
        run: gcloud run services add-iam-policy-binding $SERVICE_NAME --region=us-central1 --project $PROJECT_ID --member=allUsers --role=roles/run.invoker --platform=managed
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
